import { writeFileSync } from 'node:fs';
import { AMBIENT_ACTIONS, ANCHORS, BACKGROUND_TYPES, EASES, HARNESS_VERSION } from '../pipeline/schemas/scene.ts';
import { GENERIC_ACTIONS } from './animate.ts';
import { COMPONENTS } from './components/index.ts';
import { listStyles, loadStyle, ROLES } from './style.ts';

/**
 * Generates docs/HARNESS.md — the scene vocabulary reference, used by humans and (in M5)
 * given to the Art stage. Generated from code so it never drifts: `npm run harness:docs`.
 * A test fails when the committed file is out of date.
 */
export function harnessDocs(): string {
  const out: string[] = [];
  out.push(`# Harness reference (v${HARNESS_VERSION})`);
  out.push('');
  out.push('> Generated by `npm run harness:docs` from `harness/`. Do not edit by hand.');
  out.push('');
  out.push('A scene (`scene.json`) is declarative JSON: the harness turns it into a sanitized, animated SVG. See `docs/DESIGN.md` §9.');
  out.push('');
  out.push('## Artboard');
  out.push('');
  out.push('- Square **1080×1080**. Safe area: **60 px** margin. Labels and speech bubbles must stay inside it.');
  out.push('- At most **6 words** of text in the art (labels + bubbles). The joke lives in the phrase.');
  out.push('- Place elements with a named anchor (`"at": "left-third"`) or a normalized point (`"at": {"x": 0.3, "y": 0.8}`), or attach them to another element (`"attachTo": "bot", "side": "top"`).');
  out.push('- Grounded components (they stand on the ground line) have their origin at the **bottom center**; floating ones at their **center**.');
  out.push('- Optional per element: `scale` (0.1–4), `offset` [dx, dy] px nudge, `rotate` (deg), `flip` (mirror), `opacity`.');
  out.push('');
  out.push('### Anchors');
  out.push('');
  out.push(ANCHORS.map((a) => `\`${a}\``).join(', '));
  out.push('');
  out.push('Grid anchors are the centers of a 3×3 grid over the safe area. `left-third`, `center-third`, `right-third`, and `ground` sit on the ground line (the horizon of the background, or 78% of the height); `sky` is high in the middle.');
  out.push('');
  out.push('### Backgrounds');
  out.push('');
  out.push(`\`background.type\`: ${BACKGROUND_TYPES.map((b) => `\`${b}\``).join(', ')}. Omit it to use the style card's default. \`horizon\` (0.3–0.9) sets the ground line; \`color\`/\`color2\` take palette tokens.`);
  out.push('');
  out.push('## Components');
  out.push('');
  out.push('| Component | Grounded | Settable (`set`) | Description |');
  out.push('|---|---|---|---|');
  for (const c of Object.values(COMPONENTS)) {
    out.push(`| \`${c.name}\` | ${c.grounded ? 'yes' : 'no'} | ${(c.settable ?? []).map((s) => `\`${s}\``).join(', ') || '—'} | ${c.doc.replace(/\|/g, '\\|')} |`);
  }
  out.push('');
  out.push('## Animation');
  out.push('');
  out.push('```json');
  out.push('"animation": { "durationSec": 6, "holdSec": 2, "beats": [ { "t": 0, "target": "bot", "action": "walk-in", "from": "left" } ], "ambient": { "target": "dc", "action": "blink" } }');
  out.push('```');
  out.push('');
  out.push('- Story beats: setup → action → punchline → hold. `durationSec` 3–9 s; plays once and rests on the final frame.');
  out.push('- **The final frame must tell the joke alone** (it is the still, the social image, and the reduced-motion view).');
  out.push('- Beats on the same element and channel must not overlap in time. Each beat may set `dur` (s) and `ease`.');
  out.push(`- Eases: ${EASES.map((e) => `\`${e}\``).join(', ')}.`);
  out.push(`- \`ambient\` (optional, max one element): ${AMBIENT_ACTIONS.map((a) => `\`${a}\``).join(', ')} — a slow loop that prefers a component part (lights, antenna, rays, steam).`);
  out.push('');
  out.push('### Actions for every component');
  out.push('');
  out.push('| Action | Default dur | Effect |');
  out.push('|---|---|---|');
  for (const [name, a] of Object.entries(GENERIC_ACTIONS)) out.push(`| \`${name}\` | ${a.dur}s | ${a.doc} |`);
  out.push('');
  out.push('### Component actions');
  out.push('');
  for (const c of Object.values(COMPONENTS)) {
    for (const [name, a] of Object.entries(c.actions ?? {})) out.push(`- \`${c.name}\` → \`${name}\` (${a.dur}s): ${a.doc}`);
  }
  out.push('');
  out.push('## Style cards');
  out.push('');
  out.push(`Components draw with roles, never literal colors: ${ROLES.map((r) => `\`r-${r}\``).join(', ')}. Raw SVG should use these classes too.`);
  out.push('');
  for (const id of listStyles()) {
    const s = loadStyle(id);
    out.push(`### \`${s.id}\` — ${s.name}`);
    out.push('');
    out.push(s.description);
    out.push('');
    out.push(`- Mood: ${s.mood.join(', ')}`);
    out.push(`- Palette: ${Object.entries(s.palette).map(([k, v]) => `${k} \`${v}\``).join(', ')}`);
    out.push(`- Font: ${s.font} · default background: ${s.background.type} · texture: ${s.texture} · shadow: ${s.shadow}`);
    out.push('');
  }
  out.push('## Raw SVG (escape hatch)');
  out.push('');
  out.push('`{"id": "x", "component": "raw", "at": "center", "props": {"width": 200, "height": 120}, "svg": "<path class=\\"r-accent\\" d=\\"…\\"/>"}` — drawn in a local 0..width × 0..height box. Max 12 KB each, max 5 per scene, no `<text>`/`<style>`/scripts, palette colors only. Ids are namespaced automatically. Props (a gavel, a box of files, a badge, a door) are meant to be improvised here, differently every day.');
  out.push('');
  return out.join('\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync('docs/HARNESS.md', harnessDocs());
  console.log('wrote docs/HARNESS.md');
}
